[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "seongsu-agent"
source = "."

[services.variables]
POSTGRES_DSN = "${{POSTGRES_DSN}}"
YOUTUBE_API_KEY = "${{YOUTUBE_API_KEY}}"
LOG_LEVEL = "INFO"
RAILWAY_ENVIRONMENT = "production"

# Optional: Alerts
SLACK_WEBHOOK_URL = "${{SLACK_WEBHOOK_URL}}"
EMAIL_USER = "${{EMAIL_USER}}"
EMAIL_PASSWORD = "${{EMAIL_PASSWORD}}"
EMAIL_RECIPIENTS = "${{EMAIL_RECIPIENTS}}"

[services.healthcheck]
path = "/health"
interval = 300
timeout = 30
retries = 3