[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "kwave-production"
source = "."
build = "pip install -r requirements.txt"
start = "python kwave_production_agent.py"

[services.variables]
PYTHONPATH = "/app"
RAILWAY_ENVIRONMENT = "production"