'use client'

import { useEffect, useState } from 'react'
import Navigation from '../components/Navigation'

export default function SimpleLanding() {
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
  }, [])

  return (
    <div className="min-h-screen bg-white">
      <Navigation currentPage="home" />

      {/* Hero - Strategic Focus */}
      <section className="pt-40 pb-32 px-8">
        <div className="max-w-7xl mx-auto">
          <div className={`text-center space-y-16 ${mounted ? 'animate-fade-in-up' : 'opacity-0'}`}>
            
            {/* Problem Statement */}
            <div className="max-w-5xl mx-auto">
              <h1 className="text-7xl md:text-8xl font-light leading-[0.85] tracking-tight mb-8">
                Launch before<br/>
                <span className="text-gray-400">your competition</span>
              </h1>
              
              <p className="text-2xl text-gray-600 font-light max-w-3xl mx-auto mb-12">
                Korean coffee trends reach US markets 2-6 months later.<br/>
                Get the exact recipes and launch first.
              </p>
              
              <a 
                href="/coffee-trends" 
                className="inline-block bg-black text-white px-12 py-4 rounded-full text-lg hover:scale-105 transition-transform"
              >
                View current trends
              </a>
            </div>

            {/* Proof Point */}
            <div className="pt-16">
              <div className="inline-flex items-baseline gap-6">
                <span className="text-6xl font-light">$2.1M</span>
                <div className="text-left">
                  <div className="text-lg text-gray-600">generated by customers</div>
                  <div className="text-sm text-gray-500">240+ coffee shops</div>
                </div>
              </div>
            </div>

          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-32 px-8">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-20">
            <h2 className="text-4xl font-light tracking-tight mb-6">Complete launch package</h2>
            <p className="text-xl text-gray-600 font-light">Everything you need to launch profitably</p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-16">
            {[
              { 
                step: '01',
                title: 'Get trends', 
                description: 'Four ready-to-launch drinks with complete recipes and exact measurements' 
              },
              { 
                step: '02',
                title: 'Source ingredients', 
                description: 'Verified supplier contacts with pricing and quality specifications' 
              },
              { 
                step: '03',
                title: 'Launch first', 
                description: '2-6 month head start over competition with 70-80% margins' 
              }
            ].map((item, i) => (
              <div key={i} className="text-center">
                <div className="text-sm text-gray-400 font-mono mb-4">{item.step}</div>
                <h3 className="text-2xl font-light mb-4">{item.title}</h3>
                <p className="text-gray-600 leading-relaxed">{item.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Social Proof */}
      <section className="py-32 px-8 gradient-cool">
        <div className="max-w-7xl mx-auto text-center">
          <h2 className="text-4xl font-light tracking-tight mb-16">Proven results</h2>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-16 mb-16">
            {[
              { metric: '89%', context: 'Success rate', detail: 'Profitable within 30 days' },
              { metric: '4 months', context: 'Head start', detail: 'Average market advantage' },
              { metric: '$18K', context: 'First month', detail: 'Average additional revenue' }
            ].map((item, i) => (
              <div key={i} className="">
                <div className="text-5xl font-light mb-3">{item.metric}</div>
                <div className="text-lg text-gray-900 mb-1">{item.context}</div>
                <div className="text-sm text-gray-600">{item.detail}</div>
              </div>
            ))}
          </div>
          
          <p className="text-gray-600">Join 240+ coffee professionals launching first</p>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-32 px-8 bg-black text-white">
        <div className="max-w-7xl mx-auto text-center">
          <div className="max-w-3xl mx-auto space-y-8">
            <h2 className="text-5xl md:text-6xl font-light leading-tight">
              Start launching<br/>profitable drinks
            </h2>
            <p className="text-xl text-gray-400 font-light">
              $97/month for complete trend intelligence
            </p>
            <div className="pt-8">
              <a 
                href="/coffee-trends" 
                className="inline-block bg-white text-black px-12 py-4 rounded-full text-lg hover:scale-105 transition-transform"
              >
                View current trends
              </a>
            </div>
            <p className="text-sm text-gray-500">Cancel anytime. ROI guaranteed or full refund.</p>
          </div>
        </div>
      </section>

      {/* Footer - Minimal */}
      <footer className="py-16 px-8 border-t border-gray-100">
        <div className="max-w-7xl mx-auto">
          <div className="flex justify-between items-center">
            <div className="text-xs text-gray-400">© 2024 First Launch</div>
            <div className="flex gap-8">
              <a href="/admin" className="text-xs text-gray-400 hover:text-gray-600">Admin</a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}