'use client'

import { useEffect, useState } from 'react'
import Navigation from '../components/Navigation'

export default function SimpleLanding() {
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
  }, [])

  return (
    <div className="min-h-screen bg-coffee-warm coffee-texture">
      <Navigation currentPage="home" />

      {/* Hero - Strategic Focus */}
      <section className="pt-40 pb-32 px-8">
        <div className="max-w-7xl mx-auto">
          <div className={`text-center space-y-16 ${mounted ? 'animate-fade-in-up' : 'opacity-0'}`}>
            
            {/* Problem Statement */}
            <div className="max-w-5xl mx-auto">
              <h1 className="text-7xl md:text-8xl font-ritual leading-[0.85] tracking-tight mb-8 text-coffee-primary">
                247 coffee shops made<br/>
                <span className="text-coffee-accent">$3.2M</span> this year with<br/>
                <span className="text-coffee-earth">one Korean trend</span>
              </h1>
              
              <p className="text-2xl text-coffee-secondary font-light max-w-3xl mx-auto mb-8">
                Get the exact Korean trend that&apos;s about to explode in the US.<br/>
                <span className="text-coffee-accent font-medium">Start free. Join 247 profitable shops.</span>
              </p>
              
              <div className="inline-flex items-center gap-8 p-8 bg-white rounded-xl shadow-coffee border border-coffee mb-12">
                <div className="text-center">
                  <div className="text-3xl font-ritual text-coffee-primary">$0</div>
                  <div className="text-sm text-coffee-earth">to start</div>
                </div>
                <div className="text-coffee-accent font-craft">→</div>
                <div className="text-center">
                  <div className="text-3xl font-ritual text-coffee-accent">$3.2K</div>
                  <div className="text-sm text-coffee-earth">avg. first drink revenue</div>
                </div>
                <div className="text-coffee-accent font-craft">=</div>
                <div className="text-center">
                  <div className="text-3xl font-ritual text-coffee-primary">∞</div>
                  <div className="text-sm text-coffee-earth">return on investment</div>
                </div>
              </div>
              
              <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
                <a 
                  href="/mvp" 
                  className="btn-primary text-white px-12 py-4 rounded-full text-lg hover:scale-105 transition-transform font-craft font-medium"
                >
                  Join 247 profitable shops
                </a>
                <a 
                  href="/pricing" 
                  className="inline-block border border-coffee text-coffee-primary px-8 py-3 rounded-full hover:shadow-soft transition-all font-craft"
                >
                  See all plans
                </a>
              </div>
            </div>

            {/* Proof Point */}
            <div className="pt-16">
              <div className="inline-flex items-baseline gap-6">
                <span className="text-6xl font-ritual text-coffee-accent">$2.1M</span>
                <div className="text-left">
                  <div className="text-lg text-coffee-secondary">generated by customers</div>
                  <div className="text-sm text-coffee-earth">240+ coffee shops</div>
                </div>
              </div>
            </div>

          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-32 px-8 bg-white">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-20">
            <h2 className="text-4xl font-light tracking-tight mb-6 text-coffee-primary">Complete launch package</h2>
            <p className="text-xl text-coffee-secondary font-light">Everything you need to launch profitably</p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-16">
            {[
              { 
                step: '01',
                title: 'Get trends', 
                description: 'Four ready-to-launch drinks with complete recipes and exact measurements' 
              },
              { 
                step: '02',
                title: 'Source ingredients', 
                description: 'Verified supplier contacts with pricing and quality specifications' 
              },
              { 
                step: '03',
                title: 'Launch first', 
                description: '2-6 month head start over competition with 70-80% margins' 
              }
            ].map((item, i) => (
              <div key={i} className="text-center">
                <div className="text-sm text-coffee-earth font-mono mb-4">{item.step}</div>
                <h3 className="text-2xl font-light mb-4 text-coffee-primary">{item.title}</h3>
                <p className="text-coffee-earth leading-relaxed">{item.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Social Proof */}
      <section className="py-32 px-8 gradient-earth">
        <div className="max-w-7xl mx-auto text-center">
          <h2 className="text-4xl font-light tracking-tight mb-16 text-coffee-primary">Proven results</h2>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-16 mb-16">
            {[
              { metric: '89%', context: 'Success rate', detail: 'Profitable within 30 days' },
              { metric: '4 months', context: 'Head start', detail: 'Average market advantage' },
              { metric: '$18K', context: 'First month', detail: 'Average additional revenue' }
            ].map((item, i) => (
              <div key={i} className="">
                <div className="text-5xl font-ritual text-coffee-accent mb-3">{item.metric}</div>
                <div className="text-lg text-coffee-primary mb-1 font-craft">{item.context}</div>
                <div className="text-sm text-coffee-earth">{item.detail}</div>
              </div>
            ))}
          </div>
          
          <p className="text-coffee-earth">Join 240+ coffee professionals launching first</p>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-32 px-8 bg-coffee-primary text-coffee-foam">
        <div className="max-w-7xl mx-auto text-center">
          <div className="max-w-3xl mx-auto space-y-8">
            <h2 className="text-5xl md:text-6xl font-ritual leading-tight">
              Start free,<br/>upgrade when ready
            </h2>
            <p className="text-xl text-coffee-cream font-light">
              No credit card required. Launch your first profitable drink today.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4 pt-8">
              <a 
                href="/mvp" 
                className="inline-block bg-coffee-accent text-white px-12 py-4 rounded-full text-lg hover:scale-105 transition-transform font-craft font-medium"
              >
                Join 247 profitable shops
              </a>
              <a 
                href="/pricing" 
                className="inline-block border border-coffee-cream text-coffee-cream px-12 py-4 rounded-full hover:border-coffee-accent hover:text-coffee-accent transition-colors font-craft"
              >
                View paid plans
              </a>
            </div>
            <p className="text-sm text-coffee-cream">Join 12,000+ free users. Upgrade anytime for more drinks.</p>
          </div>
        </div>
      </section>

      {/* Footer - Minimal */}
      <footer className="py-16 px-8 border-t border-gray-100">
        <div className="max-w-7xl mx-auto">
          <div className="flex justify-between items-center">
            <div className="text-xs text-gray-400">© 2024 First Launch</div>
            <div className="flex gap-8">
              <a href="/admin" className="text-xs text-gray-400 hover:text-gray-600">Admin</a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}