name: Deploy Korean Coffee Trends

on:
  push:
    branches: [ main ]

jobs:
  deploy-vercel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        
  health-check:
    needs: [deploy-vercel]
    runs-on: ubuntu-latest
    steps:
    - name: Health Check
      run: |
        echo "🚀 Korean Coffee Trends deployment complete!"
        echo "☕ Live at: https://seongsucoffee-1.vercel.app"
        echo "🎯 Simple, focused, fast!"